### ISSUE TITLE
Please update - Backend implemention on firebase.

### ISSUE THREAD

**Issue by prohealthbox** [mjunaidsalaat/TheFoodShop#5]
Hi ,

For newbies like me , your app is really good to learn.
Please update setting up Backend implemention on firebase.
or JSON file.

Thanks,
Arjun

**Comment by JSalaat** [comment]
Hey @prohealthbox Arjun,

Thanks for the compliment. I'll surely update this ASAP when I get some time.

Thanks
JSalaat

**Comment by JSalaat** [comment]
@SdSalaat Please look into this issue and close this once it is resolved.

**Comment by SdSalaat** [comment]
@prohealthbox  The issue is resolved Please Check it now because the merge request is also accepted in master branch
